name: Cleanup Merged Branches

on:
  pull_request:
    types: [closed]
    branches:
      - release
      - master

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write # Grant write permission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.email "fozilzayniddinov7777@gmail.com"
          git config --global user.name "Fozil Zayniddinov"

      - name: Get and print the branch name for debugging
        run: |
          echo "Branch to be deleted: ${{ github.event.pull_request.head.ref }}"
          echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Delete merged branch
        if: env.BRANCH_NAME != 'release' && env.BRANCH_NAME != 'master'
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git
          git push origin --delete ${{ github.event.pull_request.head.ref }}
