name: Sync Release Branch

on:
  push:
    branches:
      - main

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout release branch
        run: |
          git fetch origin
          git checkout release || git checkout -b release

      - name: Merge main into release branch
        run: |
          git merge origin/main --no-edit

      - name: Push changes
        run: |
          git push origin release
