name: Deploy Preview

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  SHOPIFY_FLAG_STORE: "fozil-dev-store.myshopify.com"
  SHOPIFY_CLI_TTY: 0
  SHOPIFY_CLI_THEME_TOKEN: "shptka_471712c9b9d0005765e7e31c5363ef77"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub Refs
        uses: rlespinasse/github-slug-action@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: latest

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Update Theme
        if: github.event.action == 'synchronize'
        run: shopify theme push --path ./ --theme git-${{ env.GITHUB_HEAD_REF_SLUG_URL }}
