name: Sync Release Branch

on:
  push:
    branches:
      - master

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "Fozil Zayniddinov"
          git config --global user.email "fozilzayniddinov7777@gmail.com"

      - name: Checkout release branch
        run: |
          git fetch origin
          git checkout release || git checkout -b release

      - name: Merge main into release branch
        run: |
          git merge origin/master

      - name: Push changes
        run: |
          git push origin release
