name: Sync Release Branch

on:
  push:
    branches: [master]
    
permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "Fozil Zayniddinov"
          git config user.email "fozilzayniddinov7777@gmail.com"

      - name: Update Release Branch
        run: |
          git checkout master
          git fetch origin
          git checkout release
          git pull
          git merge origin/master
          git push origin release